---
extraction:
  cpp:
    prepare:
      packages:
        - gcc
        - libglib2.0-dev
    index:
      build_command:
        - meson -Ddfuzzer-test-server=true build
        - ninja -C build -v
        
